### ISSUE TITLE
Is this all ready working on Homey? 

### ISSUE THREAD

**Issue by powermarcel10** [fantomnotabene/HomeyCONZ#1]
Hello! 

Sorry for spamming you here with creating a bug report but I saw no other way to contact you. 

I am using a homey for some time now and it great. Only the current zigbee implementation is so bad, so I ordered a conbee 2 stick and a raspberry pi 4 to run home assistant and connect that to homey using the home assistent app for homey wich I have installed using CLI. 

But than I saw you app on github! Will this app communicate directly to the DeCONZ software wich can be installed on the pi without using home assistant? And, is this app already finished and working? Or still work in progress.. I'm really curious! 

Best regards, 
Marcel

**Comment by notabene00** [comment]
Hi, Marcel

Yes, this app is communicating with deCONZ rest API directly
And yes, it works right now, but there's still a lot of work
Because support for devices is adding separately for almost each one
___
In fact, my email may be found in
https://github.com/fantomnotabene/HomeyCONZ/blob/ee8c3cc7e3a003146dd60dc6093b3bd98c4f6bf3/app.json#L22

But I agree that contacts should be somewhere in sight
